import { Router } from "express";
import { adminClient } from "../db/client";
import { addLog } from "../middleware/logger";

const router = Router();

// POST /api/users/register
router.post("/register", async (req, res) => {
  const { email, phone_number } = req.body;
  if (!email) return res.status(400).json({ error: "Email is required." });

  try {
    const cleanEmail = email.trim().toLowerCase();
    const cleanPhone = (phone_number || "").trim();

    // Check if user profile already exists
    const { data: existing } = await adminClient
      .from("users")
      .select("user_id")
      .eq("email", cleanEmail)
      .maybeSingle();

    if (existing) {
      return res.status(400).json({ error: "This email is already registered. Please sign in." });
    }

    // Create user profile (user_id is UUID generated by PostgreSQL)
    const { data: user, error } = await adminClient
      .from("users")
      .insert({ email: cleanEmail, phone_number: cleanPhone })
      .select()
      .single();

    if (error) throw error;

    // Allocate Free Plan credits (50 credits, 30 day reset)
    const resetDate = new Date(Date.now() + 30 * 24 * 3600 * 1000).toISOString();
    await adminClient.from("user_credits").insert({
      user_id: user.user_id,
      plan_id: 1,
      remaining_credits: 50,
      period_reset_date: resetDate,
    });

    addLog("Database", `New user registered: ${cleanEmail} (50 Free Credits)`, "SUCCESS");
    res.json({ success: true, user });
  } catch (err: any) {
    addLog("Database", `Registration error: ${err.message}`, "ERROR");
    res.status(500).json({ error: err.message });
  }
});

// POST /api/users/login
router.post("/login", async (req, res) => {
  const { email } = req.body;
  if (!email) return res.status(400).json({ error: "Email is required." });

  try {
    const cleanEmail = email.trim().toLowerCase();

    const { data: user, error } = await adminClient
      .from("users")
      .select("*")
      .eq("email", cleanEmail)
      .maybeSingle();

    if (error) throw error;
    if (!user) {
      return res.status(404).json({ error: "No account found with this email. Please register first." });
    }

    addLog("Database", `User logged in: ${cleanEmail}`, "INFO");
    res.json({ success: true, user });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// GET /api/users/validate?user_id=...
router.get("/validate", async (req, res) => {
  const { user_id } = req.query;
  if (!user_id) return res.status(400).json({ valid: false });

  const { data } = await adminClient
    .from("users")
    .select("user_id")
    .eq("user_id", user_id as string)
    .maybeSingle();

  res.json({ valid: !!data });
});

export default router;
