/**
 * Server-side database row types.
 * These reflect the Supabase PostgreSQL schema in supabase/migrations/001_initial_schema.sql.
 * Shared domain types used by the frontend live in src/types.ts.
 */

export type SubscriptionPlan = {
  plan_id: number;
  name: string;
  price_usd: number;
  price_kes: number;
  total_credit_allocation: number;
};

export type UserRow = {
  user_id: string;       // UUID
  email: string;
  phone_number: string | null;
  created_at: string;    // ISO timestamp
};

export type UserCreditRow = {
  user_id: string;       // UUID
  plan_id: number;
  remaining_credits: number;
  period_reset_date: string;
};

export type TransactionRow = {
  transaction_id: string;                          // UUID (generated by PostgreSQL)
  user_id: string;                                 // UUID
  payment_gateway: "mpesa" | "stripe" | "paypal";
  gateway_reference: string | null;
  amount: number;
  currency: string;
  status: "Pending" | "Completed" | "Failed";
  created_at: string;
};

export type CreationRow = {
  creation_id: string;   // UUID
  user_id: string;       // UUID
  type: string;
  prompt: string | null;
  caption: string | null;
  image_url: string | null;
  video_url: string | null;
  created_at: string;
};
